export const SAVED_SEARCH_QUEUE = 'saved-search';
export const SAVED_SEARCH_QUEUE_QUEUE_LIMITTER_MAX = 1;
export const SAVED_SEARCH_QUEUE_QUEUE_LIMITTER_DURATION = 1000;

export enum SAVED_SEARCH_QUEUE_JOB {
    SAVED_SEARCH_NEW_MATCHING = 'saved-search.SAVED_SEARCH_NEW_MATCHING',
}
