version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks:
      - nestjs-rest-cqrs

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - nestjs-rest-cqrs

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    command: mysqld --innodb-default-row-format=DYNAMIC --innodb-log-file-size=256M --innodb-strict-mode=0 --character-set-server=latin1 --collation-server=latin1_swedish_ci
    networks:
      - nestjs-rest-cqrs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - nestjs-rest-cqrs

networks:
  nestjs-rest-cqrs:
    driver: bridge
